//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms
    {
        public int sms_id { get; set; }
        public int device_id { get; set; }
        public string message_text { get; set; }
        public string mobile_number { get; set; }
        public int sms_type_id { get; set; }
        public byte[] sms_timestamp { get; set; }
    
        public virtual device device { get; set; }
        public virtual smstype smstype { get; set; }
    }
}
