//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscription
    {
        public long subscription_id { get; set; }
        public long user_id { get; set; }
        public int service_id { get; set; }
        public Nullable<System.DateTime> subcription_date { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual services services { get; set; }
        public virtual user user { get; set; }
    }
}
